from pytapo import Tapo

user = "" # user you set in Advanced Settings -> Camera Account
password = "" # password you set in Advanced Settings -> Camera Account
host1 = "" # ip of the camera, example: 192.168.1.52
host2 = "" # ip of the camera, example: 192.168.1.52
host3 = "" # ip of the camera, example: 192.168.1.52
host4 = "" # ip of the camera, example: 192.168.1.52

tapoH1 = Tapo(host1, user, password)
tapoH2 = Tapo(host2, user, password)
tapoH3 = Tapo(host3, user, password)
tapoH4 = Tapo(host4, user, password)

print(tapoH1.setPrivacyMode("enabled"))
print(tapoH2.setPrivacyMode("enabled"))
print(tapoH3.setPrivacyMode("enabled"))
print(tapoH4.setPrivacyMode("enabled"))

f = open("path to file state", "a")
f.write("Privacy active on all cameras! Generated by tapo-privacy-xxxx.py as statefile")
f.close()

import requests

url = 'discord webhook url'
myobj = {'content': 'Tapo kameror har ändrat läge till privat'}

x = requests.post(url, json = myobj)

print(x.text)